package sde

type AgentInSpace struct{}
type AgentType struct{}
type Ancestry struct{}
type Bloodline struct{}
type Blueprint struct{}
type Category struct{}
type Certificate struct{}
type CharacterAttribute struct{}
type ContrabandType struct{}
type ControlTowerResource struct{}
type CorporationActivity struct{}
type DbuffCollection struct{}
type DogmaAttribute struct{}
type DogmaAttributeCategory struct{}
type DogmaEffect struct{}
type DogmaUnit struct{}
type DynamicItemAttribute struct{}
type Faction struct{}
type Graphic struct{}
type Icon struct{}
type Landmark struct{}
type MapAsteroidBelt struct{}
type MapContellation struct{}
type MapMoon struct{}
type MapPlanet struct{}
type MapRegion struct{}
type MapSolarSystem struct{}
type MapStar struct{}
type MapStargate struct{}
type MarketGroup struct{}
type Mastery struct{}
type MercenaryTacticalOperations struct{}
type MetaGroup struct{}
type NpcCharacter struct{}
type NpcCorporation struct{}
type NpcCorporationDivision struct{}
type NpcStation struct{}
type PlanetResource struct{}
type PlanetSchematic struct{}
type Race struct{}
type Skin struct{}
type SkinLicense struct{}
type SkinMaterial struct{}
type SovereigntyUpgrade struct{}
type StationOperation struct{}
type StationService struct{}
type TranslationLanguage struct{}
type TypeBonus struct{}
type TypeDogma struct{}
type TypeMaterial struct{}
