/*
EVE Stable Infrastructure (ESI) - tranquility

Testing CorporationProjectsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package esi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/AlHeamer/openesi/esi"
)

func Test_esi_CorporationProjectsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test CorporationProjectsAPIService GetCorporationsProjectsContribution", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var corporationId openapiclient.int64
		var projectId openapiclient.string
		var characterId openapiclient.int64

		resp, httpRes, err := apiClient.CorporationProjectsAPI.GetCorporationsProjectsContribution(context.Background(), corporationId, projectId, characterId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CorporationProjectsAPIService GetCorporationsProjectsContributors", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var corporationId openapiclient.int64
		var projectId openapiclient.string

		resp, httpRes, err := apiClient.CorporationProjectsAPI.GetCorporationsProjectsContributors(context.Background(), corporationId, projectId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CorporationProjectsAPIService GetCorporationsProjectsDetail", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var corporationId openapiclient.int64
		var projectId openapiclient.string

		resp, httpRes, err := apiClient.CorporationProjectsAPI.GetCorporationsProjectsDetail(context.Background(), corporationId, projectId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CorporationProjectsAPIService GetCorporationsProjectsListing", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var corporationId openapiclient.int64

		resp, httpRes, err := apiClient.CorporationProjectsAPI.GetCorporationsProjectsListing(context.Background(), corporationId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
