/*
EVE Stable Infrastructure (ESI) - tranquility

Testing RoutesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package esi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/AlHeamer/openesi/esi"
)

func Test_esi_RoutesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test RoutesAPIService PostRoute", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var originSystemId openapiclient.int64
		var destinationSystemId openapiclient.int64

		resp, httpRes, err := apiClient.RoutesAPI.PostRoute(context.Background(), originSystemId, destinationSystemId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
