/*
EVE Stellar Information (ESI) - tranquility

Testing SkillsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package esi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/AlHeamer/openesi/esi"
)

func Test_esi_SkillsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test SkillsAPIService GetCharactersCharacterIdAttributes", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var characterId int64

		resp, httpRes, err := apiClient.SkillsAPI.GetCharactersCharacterIdAttributes(context.Background(), characterId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SkillsAPIService GetCharactersCharacterIdSkillqueue", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var characterId int64

		resp, httpRes, err := apiClient.SkillsAPI.GetCharactersCharacterIdSkillqueue(context.Background(), characterId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SkillsAPIService GetCharactersCharacterIdSkills", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var characterId int64

		resp, httpRes, err := apiClient.SkillsAPI.GetCharactersCharacterIdSkills(context.Background(), characterId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
