/*
EVE Stable Infrastructure (ESI) - tranquility

Testing FreelanceJobsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package esi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/AlHeamer/openesi/esi"
)

func Test_esi_FreelanceJobsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test FreelanceJobsAPIService GetCharactersFreelanceJobsListing", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var characterId openapiclient.int64

		resp, httpRes, err := apiClient.FreelanceJobsAPI.GetCharactersFreelanceJobsListing(context.Background(), characterId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FreelanceJobsAPIService GetCharactersFreelanceJobsParticipation", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var characterId openapiclient.int64
		var jobId openapiclient.string

		resp, httpRes, err := apiClient.FreelanceJobsAPI.GetCharactersFreelanceJobsParticipation(context.Background(), characterId, jobId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FreelanceJobsAPIService GetCorporationsFreelanceJobsListing", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var corporationId openapiclient.int64

		resp, httpRes, err := apiClient.FreelanceJobsAPI.GetCorporationsFreelanceJobsListing(context.Background(), corporationId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FreelanceJobsAPIService GetCorporationsFreelanceJobsParticipants", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var corporationId openapiclient.int64
		var jobId openapiclient.string

		resp, httpRes, err := apiClient.FreelanceJobsAPI.GetCorporationsFreelanceJobsParticipants(context.Background(), corporationId, jobId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FreelanceJobsAPIService GetFreelanceJobsDetail", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var jobId openapiclient.string

		resp, httpRes, err := apiClient.FreelanceJobsAPI.GetFreelanceJobsDetail(context.Background(), jobId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FreelanceJobsAPIService GetFreelanceJobsListing", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.FreelanceJobsAPI.GetFreelanceJobsListing(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
