package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"log"
	"os"
	"path"
	"strconv"
	"strings"
	"time"

	"github.com/AlHeamer/sde"
)

type exportable interface {
	ToSqlValues(lang string, vals *strings.Builder)
}

const (
	argConvert = "convert"
	langEn     = "en"
)

var helpConvert string = `Convert the SDE into other formats.

Usage:
	` + path.Base(os.Args[0]) + ` convert [arguments] <directory>

Arguments are:`

func cmdConvert() {
	var (
		format string
		lang   string
		err    error
	)

	flagSet := flag.NewFlagSet(argConvert, flag.ExitOnError)
	flagSet.StringVar(&lang, "lang", langEn, "the language to export [de|en|es|fr|ja|ko|ru|zh] (check translationLanguages.jsonl)")
	//flagSet.StringVar(&format, "format", "mysql", "format to convert the SDE into (required)")
	format = "mysql"
	flagSet.Parse(os.Args[1:])

	if flagSet.Arg(0) == argHelp {
		usage(helpConvert, flagSet)
	}

	if format == "" {
		usage(helpConvert, flagSet)
	}

	inDir := flagSet.Arg(1)
	if inDir == "" {
		usage(helpConvert, flagSet)
	}
	inDir = path.Clean(inDir)
	build, err := strconv.ParseInt(strings.Trim(inDir, "./"), 10, 64)
	if err != nil {
		log.Fatal("error parsing build from provided directory")
	}

	dir, err := os.ReadDir(inDir)
	if err != nil {
		log.Fatalf("error opening dir: %s", err.Error())
	}

	for _, entry := range dir {
		file, err := os.Open(path.Join(inDir, entry.Name()))
		if err != nil {
			log.Fatal(err.Error())
		}

		switch strings.Split(entry.Name(), ".")[0] {
		case "types":
			toSql[*sde.Type](file, lang, build, "invTypes")
		case "groups":
			toSql[*sde.Group](file, lang, build, "invGroups")
		}

		file.Close()
	}
}

func toSql[T exportable](src io.Reader, lang string, build int64, tableName string) error {
	fileName := fmt.Sprintf("./%s_%s_%d.sql", tableName, lang, build)
	log.Println("exporting " + fileName)
	dst, err := os.OpenFile(fileName, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0644)
	if err != nil {
		return fmt.Errorf("error opening sql file: %w", err)
	}
	defer dst.Close()

	_, err = dst.WriteString(`
-- MySQL compatible dump generated by sdeutil

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table ` + tableName + `
--

-- DROP TABLE IF EXISTS ` + tableName + `;
TRUNCATE TABLE ` + tableName + `;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
-- TODO: replace with create
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table ` + tableName + `
--

LOCK TABLES ` + tableName + ` WRITE;
/*!40000 ALTER TABLE ` + tableName + ` DISABLE KEYS */;
`)
	if err != nil {
		return fmt.Errorf("error writing to file: %w", err)
	}

	j := json.NewDecoder(src)
	buf := strings.Builder{}
	var i int
	for j.More() {
		// only insert about 3000 rows per insert statement
		if i%3000 == 0 {
			if i != 0 {
				dst.WriteString(buf.String()[:buf.Len()-1] + ";\n")
				buf.Reset()
			}
			buf.WriteString("INSERT INTO invTypes VALUES")
		}
		i++

		var data T
		if err := j.Decode(&data); err != nil {
			return fmt.Errorf("error decoding json: %w", err)
		}

		data.ToSqlValues(lang, &buf)
		buf.WriteRune(',')
	}

	if buf.Len() > 0 {
		if _, err := dst.WriteString(buf.String()[:buf.Len()-1]); err != nil {
			return fmt.Errorf("error writing to file: %w", err)
		}
	}

	_, err = dst.WriteString(`;
/*!40000 ALTER TABLE ` + tableName + ` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- completed on ` + time.Now().Format(time.DateTime))
	if err != nil {
		return fmt.Errorf("error writing to file: %w", err)
	}

	return nil
}
