/*
EVE Stable Infrastructure (ESI) - tranquility

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2025-12-16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esi

import (
	"encoding/json"
)

// checks if the TypeId2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TypeId2{}

// TypeId2 struct for TypeId2
type TypeId2 struct {
	// Ore's type ID
	TypeId *int64 `json:"type_id,omitempty"`
}

// NewTypeId2 instantiates a new TypeId2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTypeId2() *TypeId2 {
	this := TypeId2{}
	return &this
}

// NewTypeId2WithDefaults instantiates a new TypeId2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTypeId2WithDefaults() *TypeId2 {
	this := TypeId2{}
	return &this
}

// GetTypeId returns the TypeId field value if set, zero value otherwise.
func (o *TypeId2) GetTypeId() int64 {
	if o == nil || IsNil(o.TypeId) {
		var ret int64
		return ret
	}
	return *o.TypeId
}

// GetTypeIdOk returns a tuple with the TypeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TypeId2) GetTypeIdOk() (*int64, bool) {
	if o == nil || IsNil(o.TypeId) {
		return nil, false
	}
	return o.TypeId, true
}

// HasTypeId returns a boolean if a field has been set.
func (o *TypeId2) HasTypeId() bool {
	if o != nil && !IsNil(o.TypeId) {
		return true
	}

	return false
}

// SetTypeId gets a reference to the given int64 and assigns it to the TypeId field.
func (o *TypeId2) SetTypeId(v int64) {
	o.TypeId = &v
}

func (o TypeId2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TypeId2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TypeId) {
		toSerialize["type_id"] = o.TypeId
	}
	return toSerialize, nil
}

type NullableTypeId2 struct {
	value *TypeId2
	isSet bool
}

func (v NullableTypeId2) Get() *TypeId2 {
	return v.value
}

func (v *NullableTypeId2) Set(val *TypeId2) {
	v.value = val
	v.isSet = true
}

func (v NullableTypeId2) IsSet() bool {
	return v.isSet
}

func (v *NullableTypeId2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTypeId2(val *TypeId2) *NullableTypeId2 {
	return &NullableTypeId2{value: val, isSet: true}
}

func (v NullableTypeId2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTypeId2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


