/*
EVE Stable Infrastructure (ESI) - tranquility

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2025-12-16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esi

import (
	"encoding/json"
)

// checks if the TypeId1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TypeId1{}

// TypeId1 struct for TypeId1
type TypeId1 struct {
	// Item's type ID
	TypeId *int64 `json:"type_id,omitempty"`
}

// NewTypeId1 instantiates a new TypeId1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTypeId1() *TypeId1 {
	this := TypeId1{}
	return &this
}

// NewTypeId1WithDefaults instantiates a new TypeId1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTypeId1WithDefaults() *TypeId1 {
	this := TypeId1{}
	return &this
}

// GetTypeId returns the TypeId field value if set, zero value otherwise.
func (o *TypeId1) GetTypeId() int64 {
	if o == nil || IsNil(o.TypeId) {
		var ret int64
		return ret
	}
	return *o.TypeId
}

// GetTypeIdOk returns a tuple with the TypeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TypeId1) GetTypeIdOk() (*int64, bool) {
	if o == nil || IsNil(o.TypeId) {
		return nil, false
	}
	return o.TypeId, true
}

// HasTypeId returns a boolean if a field has been set.
func (o *TypeId1) HasTypeId() bool {
	if o != nil && !IsNil(o.TypeId) {
		return true
	}

	return false
}

// SetTypeId gets a reference to the given int64 and assigns it to the TypeId field.
func (o *TypeId1) SetTypeId(v int64) {
	o.TypeId = &v
}

func (o TypeId1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TypeId1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TypeId) {
		toSerialize["type_id"] = o.TypeId
	}
	return toSerialize, nil
}

type NullableTypeId1 struct {
	value *TypeId1
	isSet bool
}

func (v NullableTypeId1) Get() *TypeId1 {
	return v.value
}

func (v *NullableTypeId1) Set(val *TypeId1) {
	v.value = val
	v.isSet = true
}

func (v NullableTypeId1) IsSet() bool {
	return v.isSet
}

func (v *NullableTypeId1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTypeId1(val *TypeId1) *NullableTypeId1 {
	return &NullableTypeId1{value: val, isSet: true}
}

func (v NullableTypeId1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTypeId1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


