/*
EVE Stable Infrastructure (ESI) - tranquility

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2025-12-16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esi

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// CorporationsProjectsDetailConfigurationminematerialMaterialsInner - struct for CorporationsProjectsDetailConfigurationminematerialMaterialsInner
type CorporationsProjectsDetailConfigurationminematerialMaterialsInner struct {
	GroupId2 *GroupId2
	TypeId2 *TypeId2
}

// GroupId2AsCorporationsProjectsDetailConfigurationminematerialMaterialsInner is a convenience function that returns GroupId2 wrapped in CorporationsProjectsDetailConfigurationminematerialMaterialsInner
func GroupId2AsCorporationsProjectsDetailConfigurationminematerialMaterialsInner(v *GroupId2) CorporationsProjectsDetailConfigurationminematerialMaterialsInner {
	return CorporationsProjectsDetailConfigurationminematerialMaterialsInner{
		GroupId2: v,
	}
}

// TypeId2AsCorporationsProjectsDetailConfigurationminematerialMaterialsInner is a convenience function that returns TypeId2 wrapped in CorporationsProjectsDetailConfigurationminematerialMaterialsInner
func TypeId2AsCorporationsProjectsDetailConfigurationminematerialMaterialsInner(v *TypeId2) CorporationsProjectsDetailConfigurationminematerialMaterialsInner {
	return CorporationsProjectsDetailConfigurationminematerialMaterialsInner{
		TypeId2: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *CorporationsProjectsDetailConfigurationminematerialMaterialsInner) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into GroupId2
	err = newStrictDecoder(data).Decode(&dst.GroupId2)
	if err == nil {
		jsonGroupId2, _ := json.Marshal(dst.GroupId2)
		if string(jsonGroupId2) == "{}" { // empty struct
			dst.GroupId2 = nil
		} else {
			if err = validator.Validate(dst.GroupId2); err != nil {
				dst.GroupId2 = nil
			} else {
				match++
			}
		}
	} else {
		dst.GroupId2 = nil
	}

	// try to unmarshal data into TypeId2
	err = newStrictDecoder(data).Decode(&dst.TypeId2)
	if err == nil {
		jsonTypeId2, _ := json.Marshal(dst.TypeId2)
		if string(jsonTypeId2) == "{}" { // empty struct
			dst.TypeId2 = nil
		} else {
			if err = validator.Validate(dst.TypeId2); err != nil {
				dst.TypeId2 = nil
			} else {
				match++
			}
		}
	} else {
		dst.TypeId2 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.GroupId2 = nil
		dst.TypeId2 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(CorporationsProjectsDetailConfigurationminematerialMaterialsInner)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(CorporationsProjectsDetailConfigurationminematerialMaterialsInner)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src CorporationsProjectsDetailConfigurationminematerialMaterialsInner) MarshalJSON() ([]byte, error) {
	if src.GroupId2 != nil {
		return json.Marshal(&src.GroupId2)
	}

	if src.TypeId2 != nil {
		return json.Marshal(&src.TypeId2)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *CorporationsProjectsDetailConfigurationminematerialMaterialsInner) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.GroupId2 != nil {
		return obj.GroupId2
	}

	if obj.TypeId2 != nil {
		return obj.TypeId2
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj CorporationsProjectsDetailConfigurationminematerialMaterialsInner) GetActualInstanceValue() (interface{}) {
	if obj.GroupId2 != nil {
		return *obj.GroupId2
	}

	if obj.TypeId2 != nil {
		return *obj.TypeId2
	}

	// all schemas are nil
	return nil
}

type NullableCorporationsProjectsDetailConfigurationminematerialMaterialsInner struct {
	value *CorporationsProjectsDetailConfigurationminematerialMaterialsInner
	isSet bool
}

func (v NullableCorporationsProjectsDetailConfigurationminematerialMaterialsInner) Get() *CorporationsProjectsDetailConfigurationminematerialMaterialsInner {
	return v.value
}

func (v *NullableCorporationsProjectsDetailConfigurationminematerialMaterialsInner) Set(val *CorporationsProjectsDetailConfigurationminematerialMaterialsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCorporationsProjectsDetailConfigurationminematerialMaterialsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCorporationsProjectsDetailConfigurationminematerialMaterialsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCorporationsProjectsDetailConfigurationminematerialMaterialsInner(val *CorporationsProjectsDetailConfigurationminematerialMaterialsInner) *NullableCorporationsProjectsDetailConfigurationminematerialMaterialsInner {
	return &NullableCorporationsProjectsDetailConfigurationminematerialMaterialsInner{value: val, isSet: true}
}

func (v NullableCorporationsProjectsDetailConfigurationminematerialMaterialsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCorporationsProjectsDetailConfigurationminematerialMaterialsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


