/*
EVE Stable Infrastructure (ESI) - tranquility

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2025-12-16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esi

import (
	"encoding/json"
)

// checks if the GroupId2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GroupId2{}

// GroupId2 struct for GroupId2
type GroupId2 struct {
	// Ore's group ID
	GroupId *int64 `json:"group_id,omitempty"`
}

// NewGroupId2 instantiates a new GroupId2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupId2() *GroupId2 {
	this := GroupId2{}
	return &this
}

// NewGroupId2WithDefaults instantiates a new GroupId2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupId2WithDefaults() *GroupId2 {
	this := GroupId2{}
	return &this
}

// GetGroupId returns the GroupId field value if set, zero value otherwise.
func (o *GroupId2) GetGroupId() int64 {
	if o == nil || IsNil(o.GroupId) {
		var ret int64
		return ret
	}
	return *o.GroupId
}

// GetGroupIdOk returns a tuple with the GroupId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupId2) GetGroupIdOk() (*int64, bool) {
	if o == nil || IsNil(o.GroupId) {
		return nil, false
	}
	return o.GroupId, true
}

// HasGroupId returns a boolean if a field has been set.
func (o *GroupId2) HasGroupId() bool {
	if o != nil && !IsNil(o.GroupId) {
		return true
	}

	return false
}

// SetGroupId gets a reference to the given int64 and assigns it to the GroupId field.
func (o *GroupId2) SetGroupId(v int64) {
	o.GroupId = &v
}

func (o GroupId2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GroupId2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.GroupId) {
		toSerialize["group_id"] = o.GroupId
	}
	return toSerialize, nil
}

type NullableGroupId2 struct {
	value *GroupId2
	isSet bool
}

func (v NullableGroupId2) Get() *GroupId2 {
	return v.value
}

func (v *NullableGroupId2) Set(val *GroupId2) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupId2) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupId2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupId2(val *GroupId2) *NullableGroupId2 {
	return &NullableGroupId2{value: val, isSet: true}
}

func (v NullableGroupId2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupId2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


